### ISSUE TITLE
Better handling of missing coverpage in Fireball

### ISSUE THREAD

**Issue by donaldgray** [dlcs/protagonist#520]
One of the legacy namedquery's for PDFs for wellcome had a `coverpage=` that no longer existed. This resulted in errors in Fireball, likely due to the resulting coverpage url returning HTML rather than a PDF. Cause will need confirmed and fixed.

```
ERROR in app: Exception on /pdf [POST]
Traceback (most recent call last):
File "/usr/local/lib/python3.10/site-packages/flask/app.py", line 2077, in wsgi_app
response = self.full_dispatch_request()
File "/usr/local/lib/python3.10/site-packages/flask/app.py", line 1525, in full_dispatch_request
rv = self.handle_user_exception(e)
File "/usr/local/lib/python3.10/site-packages/flask/app.py", line 1523, in full_dispatch_request
rv = self.dispatch_request()
File "/usr/local/lib/python3.10/site-packages/flask/app.py", line 1509, in dispatch_request
return self.ensure_sync(self.view_functions[rule.endpoint])(**req.view_args)
File "/opt/fireball/./fireball.py", line 146, in generate
merger.append(merge_input1)
File "/usr/local/lib/python3.10/site-packages/PyPDF2/_merger.py", line 244, in append
self.merge(len(self.pages), fileobj, bookmark, pages, import_bookmarks)
File "/usr/local/lib/python3.10/site-packages/PyPDF2/_merger.py", line 127, in merge
reader = PdfReader(stream, strict=self.strict) # type: ignore[arg-type]
File "/usr/local/lib/python3.10/site-packages/PyPDF2/_reader.py", line 267, in __init__
self.read(stream)
File "/usr/local/lib/python3.10/site-packages/PyPDF2/_reader.py", line 1219, in read
line = read_previous_line(stream)
File "/usr/local/lib/python3.10/site-packages/PyPDF2/_utils.py", line 187, in read_previous_line
raise PdfStreamError(STREAM_TRUNCATED_PREMATURELY)
PyPDF2.errors.PdfStreamError: Stream has ended unexpectedly
```

**Comment by tomcrane** [comment]
Task is to familiarise with fireball (Python) and investigate cause of error.

Fireball generates PDFs from names queries. Unlike IIIF named queries, a PDF might need a cover page - see https://iiif.wellcomecollection.org/pdf/b21216149
